version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-14.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file: docker-compose.env
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:10.4-14
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file: docker-compose.env
    volumes:
      - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.14.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /var/local/dcm4chee-arc/storage:/storage
  mongo:
    image: mongo:3.6
    volumes:
      - /var/local/dcm4chee-arc/mongo:/data/db
  viewer:
    image: ohif/viewer:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ohif
    depends_on:
      - mongo
      - arc
    volumes:
      - /var/local/dcm4chee-arc/ohif/app.json:/app/app.json